# Basic
title = "FPV India"
baseURL = "http://localhost:1313"
theme = "vno-hugo"

# supported languages: en-us, zh-cn (lowercase language codes only)
defaultContentLanguage = 'en-us'
# here lists available languages, if you wish to add your own custom translation, please refer to https://gohugo.io/content-management/multilingual
[languages]
  [languages.en-us]
    languageName = 'English(United States)'
    weight = 10

# Pagination
paginate = 10
paginatePath = "page"

[outputs]
  home = ["HTML", "RSS"]

[menu]
 [[menu.main]]
    name = "Events"
    identifier = "events"
    url = "/events"
    weight = 10
  [[menu.main]]
     name = "Tags"
     identifier = "Tags"
     url = "/tags/"
     weight = 20
[taxonomies]
    tag = "tags"

[params]
author = "droneflipper"
subtitle = "Welcome to the home page of FPV India community"
description = "This is where we make things fly..."
welcomeMessage = "Our goal is to regularly host high-quality races that adhere to the standards set by MultiGP, with a minimum of one event per month. We have already attracted a number of highly skilled pilots to our team, including some of the top pilots in the country. Our mission is to make FPV racing more accessible and widely available in India. We believe that by hosting regular events, we can attract new pilots and fans to the sport, and provide opportunities for the existing community to improve."


[params.Author.email]
email = "admin@fpvindia.in"

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
coverColor = "red"

#[params.comment]
#disqus = "vno-hugo"
#duoshuo = ""

[params.social]
github = "https://github.com/fpv-india"
mail = "admin@fpvindia.in"

# The blog button should not be removed.
[params.blogButton]
title = "Blog"
description = "Visit blog"

[params.copyright]
license = '© FPV India'
license_link = 'http://creativecommons.org/licenses/by-nc-sa/4.0/'

[permalinks]
posts = "/:year/:month/:title/"
